ALTER TABLE RISK_EVENT ADD DRV_LINE_ID INTEGER NULL;
ALTER TABLE ALARM_HANDLE ADD IF NOT EXISTS GROUP_NAME VARCHAR NULL;
ALTER TABLE ALARM_HANDLE ADD IF NOT EXISTS PLATE_COLOR VARCHAR NULL;
ALTER TABLE ALARM_HANDLE ADD IF NOT EXISTS VEHICLE_TYPE VARCHAR NULL;

ALTER TABLE RISK ADD IF NOT EXISTS HANDLE_TYPE VARCHAR NULL;