#菜单
INSERT INTO `zw_c_resource` (`id`, `icon_cls`, `resource_name`, `type`, `code`, `permission`, `perm_value`, `description`, `parent_id`, `sort_order`, `editable`, `enabled`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `domain`, `code_num`, `flag`) VALUES ('b2fcff5c-255a-11eb-b4ec-000c29920fdc', '', '平台巡检', '0', NULL, '', '/adas/platformInspection/list', '', 'd6770672-8165-11e7-bb31-be2e44b06b34', '7', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, '1');
INSERT INTO `zw_c_resource` (`id`, `icon_cls`, `resource_name`, `type`, `code`, `permission`, `perm_value`, `description`, `parent_id`, `sort_order`, `editable`, `enabled`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `domain`, `code_num`, `flag`) VALUES ('b2f9e987-255a-11eb-b4ec-000c29920fdc', '', '设备报修', '0', NULL, '', '/adas/equipmentRepair/list', '', 'd6770672-8165-11e7-bb31-be2e44b06b34', '8', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, '1');
INSERT INTO `zw_c_resource` (`id`, `icon_cls`, `resource_name`, `type`, `code`, `permission`, `perm_value`, `description`, `parent_id`, `sort_order`, `editable`, `enabled`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `domain`, `code_num`, `flag`) VALUES ('b2feb33f-255a-11eb-b4ec-000c29920fdc', '', '车辆与终端运行状态', '0', NULL, '', '/adas/vehicleDeviceState/list', '', '2234bd3e-191e-2216-d43f-78df4c92c74d', '14015', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, '1');

INSERT INTO `zw_c_role_resource` (`id`, `resource_id`, `role_id`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `flag`, `editable`) VALUES ('5a283935-255b-11eb-b4ec-000c29920fdc', 'b2f9e987-255a-11eb-b4ec-000c29920fdc', 'cn=ROLE_ADMIN,ou=Groups', '2020-11-13 10:50:43', 'admin', NULL, NULL, '1', '1');
INSERT INTO `zw_c_role_resource` (`id`, `resource_id`, `role_id`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `flag`, `editable`) VALUES ('0d1d9eb5-255b-11eb-b4ec-000c29920fdc', 'b2feb33f-255a-11eb-b4ec-000c29920fdc', 'cn=ROLE_ADMIN,ou=Groups', '2020-11-13 10:50:43', 'admin', NULL, NULL, '1', '1');
INSERT INTO `zw_c_role_resource` (`id`, `resource_id`, `role_id`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `flag`, `editable`) VALUES ('0d1f943d-255b-11eb-b4ec-000c29920fdc', 'b2fcff5c-255a-11eb-b4ec-000c29920fdc', 'cn=ROLE_ADMIN,ou=Groups', '2020-11-13 10:50:43', 'admin', NULL, NULL, '1', '1');


#风险事件
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e46af24-27d0-11eb-b4ec-000c29920fdc', '疲劳驾驶状态报警', '疑似疲劳', '疲劳驾驶状态报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254001', '25', '60', '1', '疲劳驾驶', '0', '8', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'fatigueDriving', '1', '0x40');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e487158-27d0-11eb-b4ec-000c29920fdc', '疲劳驾驶状态预警', '疑似疲劳', '疲劳驾驶状态预警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '-254001', '25', '60', '1', '疲劳驾驶', '5', '0', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'fatigueDriving', '-1', '0x40');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e49ff70-27d0-11eb-b4ec-000c29920fdc', '手持接打电话报警', '注意力分散', '手持接打电话报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254002', '25', '30', '2', '接打手持电话', '0', '7', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'phone', '2', '0x40');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e52253b-27d0-11eb-b4ec-000c29920fdc', '长时间不目视前方报警', '注意力分散', '长时间不目视前方报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254003', '25', '30', '2', '长时间不目视前方', '0', '9', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'abnormalPosture', '3', '0x40');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e55d6e5-27d0-11eb-b4ec-000c29920fdc', '驾驶员不在驾驶位置报警', '违规异常', '驾驶员不在驾驶位置报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254005', '25', '20', '3', '驾驶员不在驾驶位置', '0', '9', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'noDriverDetected', '4', '0x40');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e588bb5-27d0-11eb-b4ec-000c29920fdc', '抽烟报警', '注意力分散', '抽烟报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254004', '25', '30', '2', '抽烟', '0', '7', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'smoke', '5', '0x40');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e5af442-27d0-11eb-b4ec-000c29920fdc', '前向碰撞报警', '碰撞危险', '前向碰撞报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253901', '25', '50', '4', '前向碰撞', '0', '9', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'vehicleCrash', '1', '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e5d610e-27d0-11eb-b4ec-000c29920fdc', '前向碰撞预警', '碰撞危险', '前向碰撞预警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '-253901', '25', '50', '4', '前向碰撞', '4', '0', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'vehicleCrash', '-1', '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e5fe37b-27d0-11eb-b4ec-000c29920fdc', '车道偏离报警', '碰撞危险', '车道偏离报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253902', '25', '50', '4', NULL, '0', '9', '0.3', '0.4', '0.5', '30', '50', '70', NULL, NULL, '2', '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e624843-27d0-11eb-b4ec-000c29920fdc', '车道左偏离报警', '碰撞危险', '车道左偏离报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '2539021', '25', '50', '4', '车道左偏离报警', '0', '9', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'leftOffset', NULL, '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e6481f4-27d0-11eb-b4ec-000c29920fdc', '车道右偏离报警', '碰撞危险', '车道右偏离报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '2539022', '25', '50', '4', '车道右偏离报警', '0', '9', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'rightOffset', NULL, '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e66a5be-27d0-11eb-b4ec-000c29920fdc', '车道偏离预警', '碰撞危险', '车道偏离预警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '-253902', '25', '50', '4', NULL, '4', '0', '0.3', '0.4', '0.5', '30', '50', '70', NULL, NULL, '-2', '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e68d2b4-27d0-11eb-b4ec-000c29920fdc', '车道左偏离预警', '碰撞危险', '车道左偏离预警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '-2539021', '25', '50', '4', '车道左偏离预警', '4', '0', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'leftOffsetWarning', NULL, '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e6b2f53-27d0-11eb-b4ec-000c29920fdc', '车道右偏离预警', '碰撞危险', '车道右偏离预警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '-2539022', '25', '50', '4', '车道右偏离预警', '4', '0', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'rightOffsetWarning', NULL, '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e6d9689-27d0-11eb-b4ec-000c29920fdc', '超速报警', '违规异常', '超速报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253903', '25', '20', '3', '超速报警', '0', '9', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'overSpeed', '3', '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e6fd94b-27d0-11eb-b4ec-000c29920fdc', '路线偏离报警', '违规异常', '路线偏离报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253904', '25', '20', '3', '路线偏离报警', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'lineOffset', '4', '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e722b0a-27d0-11eb-b4ec-000c29920fdc', '禁行路段/区域报警', '违规异常', '禁行路段/区域报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253905', '25', '20', '3', '禁行报警', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'forbid', '5', '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e74836c-27d0-11eb-b4ec-000c29920fdc', '事故报警', '违规异常', '事故报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253906', '25', '20', '3', '设备异常', '0', '12', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'equipmentAbnormal', '6', '0x39');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e76d308-27d0-11eb-b4ec-000c29920fdc', '人证不符报警', '违规异常', '人证不符报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253801', '25', '20', '3', '人证不符', '0', '12', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'inConformityCertificate', '1', '0x38');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e790a94-27d0-11eb-b4ec-000c29920fdc', 'IC卡从业资格证读卡失败报警', '违规异常', 'IC卡从业资格证读卡失败报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253802', '25', '20', '3', '人证不符', '0', '12', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'inConformityCertificate', '2', '0x38');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e7b5033-27d0-11eb-b4ec-000c29920fdc', '遮挡失效报警', '违规异常', '遮挡失效报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254101', '25', '20', '3', '遮挡', '0', '2', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'keepOut', '1', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e7d8ec8-27d0-11eb-b4ec-000c29920fdc', '红外阻断型墨镜失效报警', '违规异常', '红外阻断型墨镜失效报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254102', '25', '20', '3', '红外阻断', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'infraredBlocking', '2', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e7fc32e-27d0-11eb-b4ec-000c29920fdc', '主存储器异常报警', '违规异常', '主存储器异常报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254103', '25', '20', '3', '设备异常', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'equipmentAbnormal', '3', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e822d54-27d0-11eb-b4ec-000c29920fdc', '备用存储器异常报警', '违规异常', '备用存储器异常报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254104', '25', '20', '3', '设备异常', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'equipmentAbnormal', '4', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e848002-27d0-11eb-b4ec-000c29920fdc', '卫星信号异常报警', '违规异常', '卫星信号异常报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254105', '25', '20', '3', '设备异常', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'equipmentAbnormal', '5', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e86ec17-27d0-11eb-b4ec-000c29920fdc', '通信信号异常报警', '违规异常', '通信信号异常报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254106', '25', '20', '3', '设备异常', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'equipmentAbnormal', '6', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e894691-27d0-11eb-b4ec-000c29920fdc', '备用电池欠压报警', '违规异常', '备用电池欠压报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254107', '25', '20', '3', '设备异常', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'equipmentAbnormal', '7', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e8b9c37-27d0-11eb-b4ec-000c29920fdc', '备用电池失效报警', '违规异常', '备用电池失效报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254108', '25', '20', '3', '设备异常', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'equipmentAbnormal', '8', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('2e8dfd4a-27d0-11eb-b4ec-000c29920fdc', 'IC卡从业资格证模块故障报警', '违规异常', 'IC卡从业资格证模块故障报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '254109', '25', '20', '3', '设备异常', '0', '3', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'equipmentAbnormal', '9', '0x41');
INSERT INTO `zw_m_risk_event` (`id`, `risk_event`, `risk_type`, `description`, `flag`, `create_data_time`, `create_data_username`, `update_data_time`, `update_data_username`, `function_id`, `protocol_type`, `interval_time`, `risk_type_num`, `event_common_name`, `one_level`, `two_level`, `one_speed_factor`, `two_speed_factor`, `three_speed_factor`, `one_speed`, `two_speed`, `three_speed`, `808_pos`, `event_common_field`, `index_pos`, `alarm_pos`) VALUES ('6fadfbd5-2974-11eb-b4ec-000c29920fdc', '人证不符报警（平台）', '违规异常', '人证不符报警危险说明', '1', '2020-11-13 17:45:01', NULL, NULL, NULL, '253803', '25', '20', '3', '人证不符', '0', '12', '0.3', '0.4', '0.5', '30', '50', '70', NULL, 'inConformityCertificate', '-100', '0x38');

#黑标协议
INSERT INTO `zw_c_dictionary` (`id`, `pid`, `code`, `value`, `type`, `description`, `sort`) VALUES ('9009cb38-ab0e-4c04-b0d3-1ab0abf9c0a6', NULL, '25', '交通部JT/T808-2019(黑标)', '808', 'activeSafety', '15');
INSERT INTO `zw_c_dictionary` (`id`, `pid`, `code`, `value`, `type`, `description`, `sort`) VALUES ('19c1a54a-8901-40cb-b3f9-b4751344bdae', NULL, '1013', '黑标-809-2019', '809', NULL, NULL);

#主动安全黑标新增事件事件
alter table zw_m_vehicle_adas_event add column over_speed int(11) DEFAULT 0 COMMENT '超速报警';
alter table zw_m_vehicle_adas_event add column line_offset int(11) DEFAULT 0 COMMENT '路线偏离报警';
alter table zw_m_vehicle_adas_event add column forbid int(11) DEFAULT 0 COMMENT '禁行报警';
alter table zw_m_vehicle_adas_event add column equipment_abnormal int(11) DEFAULT 0 COMMENT '设备异常';
alter table zw_m_vehicle_adas_event add column left_offset_warning int(11) DEFAULT 0 COMMENT '车道左偏离预警';
alter table zw_m_vehicle_adas_event add column right_offset_warning int(11) DEFAULT 0 COMMENT '车道右偏离预警';

#主动安全参数设置
alter table zw_m_adas_common_param_setting add column dynamic_contrast_interval int(11) COMMENT '动态比对间隔(s)';
alter table zw_m_adas_alarm_param_setting add column warning_time_threshold int(11) COMMENT '预警时间阈值单位s，取值范围 1~5，目前使用国标规定值 2.7';

#从业人员相关修改
ALTER TABLE `zw_m_professionals_info` ADD COLUMN `face_id`  varchar(64) DEFAULT NULL COMMENT '驾驶员人脸id';

ALTER TABLE `zw_m_vehicle_driver_identification` ADD COLUMN `face_id`  varchar(64) DEFAULT NULL NULL COMMENT '驾驶员人脸id';
ALTER TABLE `zw_m_vehicle_driver_identification` ADD COLUMN `card_number`  varchar(64) DEFAULT NULL COMMENT '从业资格证号';
ALTER TABLE `zw_m_vehicle_driver_identification` ADD COLUMN `video_url`  varchar(360) DEFAULT NULL COMMENT '视频附件地址';

#平台巡检记录表
CREATE TABLE `zw_m_platform_inspection` (
  `id` varchar(64) NOT NULL,
  `vehicle_id` varchar(64) NOT NULL COMMENT '车id',
  `inspection_type` smallint(6) DEFAULT NULL COMMENT '巡检的类型（1.车辆运行监测巡检2.驾驶员驾驶行为监测巡检 3.驾驶员身份识别巡检)',
  `inspector` varchar(50) DEFAULT NULL COMMENT '巡检人',
  `inspection_time` datetime DEFAULT NULL COMMENT '巡检时间',
  `inspection_status` smallint(6) DEFAULT NULL COMMENT '巡检状态(1下发中，2下发成功，3终端响应超时，4终端离线 )',
  `inspection_result_id` varchar(64) DEFAULT NULL COMMENT '巡检结果的表的id',
  `flag` smallint(6) DEFAULT NULL COMMENT '逻辑删除标记',
  KEY `idx_vid_time_type` (`vehicle_id`,`inspection_time`,`inspection_type`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检记录表';

#巡检结果表
CREATE TABLE `zw_m_platform_inspection_result` (
  `id` varchar(64) NOT NULL,
  `vehicle_id` varchar(64) NOT NULL COMMENT '车id',
  `image_url` varchar(360) DEFAULT NULL COMMENT '图片附件地址',
  `video_url` varchar(360) DEFAULT NULL COMMENT '视频附件地址',
  `time` datetime DEFAULT NULL COMMENT '时间',
  `alarm_type` smallint(6) DEFAULT NULL COMMENT '报警类型',
  `warn_type` smallint(6) DEFAULT NULL COMMENT '预警类型',
  `remind_flag` smallint(6) DEFAULT NULL COMMENT '是否有效提醒驾驶员',
   `type` smallint(6) DEFAULT NULL COMMENT '道路偏离类型（1 左侧偏离 2右侧偏离）禁行类型(1 禁行区域， 2禁行)',
  `status` smallint(6) DEFAULT NULL COMMENT '标志（1开始标志 2持续标志 3 结束标志）',
  `route_id` varchar(64) DEFAULT NULL COMMENT '线路/区域 id',
  `driver_id` varchar(64) DEFAULT NULL COMMENT '驾驶员id',
  `inspection_type` smallint(6) DEFAULT NULL COMMENT '巡检类型（1.车辆运行监测巡检2.驾驶员驾驶行为监测巡检）'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检结果表';

#黑标默认参数定义设置
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('2fb4fea4-2ef6-11eb-b4ec-000c29920fdc', 'default', '254109', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('2fbca839-2ef6-11eb-b4ec-000c29920fdc', 'default', '254108', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('2fcbfeb6-2ef6-11eb-b4ec-000c29920fdc', 'default', '254107', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('2fd6b6c1-2ef6-11eb-b4ec-000c29920fdc', 'default', '254106', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('2fe5acda-2ef6-11eb-b4ec-000c29920fdc', 'default', '254105', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('2fecbfaa-2ef6-11eb-b4ec-000c29920fdc', 'default', '254104', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('2ff3267e-2ef6-11eb-b4ec-000c29920fdc', 'default', '254103', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('2ff85567-2ef6-11eb-b4ec-000c29920fdc', 'default', '254102', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, '60', NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('30012552-2ef6-11eb-b4ec-000c29920fdc', 'default', '254101', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, '60', NULL, NULL, NULL, NULL, '41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('3006b421-2ef6-11eb-b4ec-000c29920fdc', 'default', '254005', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '40', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('300bc4cc-2ef6-11eb-b4ec-000c29920fdc', 'default', '254004', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, '60', NULL, NULL, NULL, NULL, '40', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('3010bc4a-2ef6-11eb-b4ec-000c29920fdc', 'default', '254003', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '40', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('30168a01-2ef6-11eb-b4ec-000c29920fdc', 'default', '254002', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, '60', NULL, NULL, NULL, NULL, '40', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('301d9fb0-2ef6-11eb-b4ec-000c29920fdc', 'default', '254001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '40', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('3022f3c3-2ef6-11eb-b4ec-000c29920fdc', 'default', '253905', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '39', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('3027be70-2ef6-11eb-b4ec-000c29920fdc', 'default', '253904', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '39', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('302cbd94-2ef6-11eb-b4ec-000c29920fdc', 'default', '253903', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '39', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('3033309e-2ef6-11eb-b4ec-000c29920fdc', 'default', '253902', NULL, NULL, NULL, NULL, '50', NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '39', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('30386f28-2ef6-11eb-b4ec-000c29920fdc', 'default', '253901', NULL, NULL, '27', NULL, '50', NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '39', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '27');
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('303d72ab-2ef6-11eb-b4ec-000c29920fdc', 'default', '253802', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '38', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_alarm_param_setting` (`id`, `vehicle_id`, `risk_function_id`, `alarm_enable`, `gravity_acceleration_threshold`, `time_threshold`, `engine_threshold`, `speed_threshold`, `one_level_alarm_enable`, `two_level_alarm_enable`, `video_recording_time`, `photograph_number`, `photograph_time`, `time_distance_threshold`, `time_slot_threshold`, `alarm_level_speed_threshold`, `frequency_threshold`, `touch_status`, `road_sign_recognition`, `param_type`, `flag`, `road_sign_enable`, `create_time`, `update_time`, `tyre_number`, `unit`, `pressure`, `pressure_threshold`, `slow_leak_threshold`, `low_pressure`, `high_pressure`, `high_temperature`, `electricity_threshold`, `upload_time`, `rear`, `sideRear`, `primary_channel`, `subcode_channel`, `capture_channel`, `day_time`, `night_time`, `min_stop_time`, `night_time_value`, `one_day_drive_time`, `auxiliary_enable`, `voice_reminder_enable`, `one_level_voice_reminder`, `two_level_voice_reminder`, `one_level_auxiliary_multimedia`, `two_level_auxiliary_multimedia`, `compensating_enable`, `smoothing`, `automatic_upload_time`, `compensation_factor_k`, `compensation_factor_b`, `left_distance`, `right_distance`, `warning_time_threshold`) VALUES ('30438e9b-2ef6-11eb-b4ec-000c29920fdc', 'default', '253801', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '3', '2', NULL, NULL, NULL, NULL, NULL, NULL, '38', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO `zw_m_adas_common_param_setting` (`id`, `vehicle_id`, `camera_resolution`, `video_resolution`, `alarm_volume`, `touch_status`, `photograph_number`, `photograph_time`, `timing_photo_interval`, `distance_photo_interval`, `flag`, `speed_limit`, `protocol_type`, `param_type`, `create_time`, `update_time`, `sensitivity`, `recording_time`, `channel_one`, `channel_two`, `channel_three`, `dynamic_contrast_interval`) VALUES ('3737d9f7-2ef6-11eb-b4ec-000c29920fdc', 'default', '0x01', '0x01', '6', NULL, NULL, NULL, NULL, NULL, '1', '5', '25', '38', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1200');
INSERT INTO `zw_m_adas_common_param_setting` (`id`, `vehicle_id`, `camera_resolution`, `video_resolution`, `alarm_volume`, `touch_status`, `photograph_number`, `photograph_time`, `timing_photo_interval`, `distance_photo_interval`, `flag`, `speed_limit`, `protocol_type`, `param_type`, `create_time`, `update_time`, `sensitivity`, `recording_time`, `channel_one`, `channel_two`, `channel_three`, `dynamic_contrast_interval`) VALUES ('373bf84b-2ef6-11eb-b4ec-000c29920fdc', 'default', '0x01', '0x01', '6', NULL, NULL, NULL, NULL, NULL, '1', '5', '25', '39', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_common_param_setting` (`id`, `vehicle_id`, `camera_resolution`, `video_resolution`, `alarm_volume`, `touch_status`, `photograph_number`, `photograph_time`, `timing_photo_interval`, `distance_photo_interval`, `flag`, `speed_limit`, `protocol_type`, `param_type`, `create_time`, `update_time`, `sensitivity`, `recording_time`, `channel_one`, `channel_two`, `channel_three`, `dynamic_contrast_interval`) VALUES ('373e9048-2ef6-11eb-b4ec-000c29920fdc', 'default', '0x01', '0x01', '6', NULL, NULL, NULL, NULL, NULL, '1', '5', '25', '40', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `zw_m_adas_common_param_setting` (`id`, `vehicle_id`, `camera_resolution`, `video_resolution`, `alarm_volume`, `touch_status`, `photograph_number`, `photograph_time`, `timing_photo_interval`, `distance_photo_interval`, `flag`, `speed_limit`, `protocol_type`, `param_type`, `create_time`, `update_time`, `sensitivity`, `recording_time`, `channel_one`, `channel_two`, `channel_three`, `dynamic_contrast_interval`) VALUES ('37440a86-2ef6-11eb-b4ec-000c29920fdc', 'default', '0x01', '0x01', '6', NULL, NULL, NULL, NULL, NULL, '1', '5', '25', '41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

ALTER TABLE zw_m_media modify COLUMN `media_id` bigint(20) DEFAULT NULL COMMENT '多媒体id';



