package com.zw.adas.domain.define.setting;

import lombok.Data;

import java.io.Serializable;
import java.util.UUID;

/**
 * generated by gfw
 * Date: Tue Jun 11 09:30:02 CST 2019
 * @author gfw
 */

@Data
public class AdasAlarmParamSetting implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 表id
     */
    private String id = UUID.randomUUID().toString();

    /**
     * 车辆id
     **/
    private String vehicleId;

    /**
     * 风险事件(function_id)
     **/
    private Integer riskFunctionId;

    /**
     * 报警开关
     **/
    private Integer alarmEnable;

    /**
     * 重力加速度阈值
     **/
    private String gravityAccelerationThreshold;

    /**
     * 时间阈值
     **/
    private Integer timeThreshold;

    /**
     * 发动机转速阈值 离线人脸比对
     **/
    private String engineThreshold;

    /**
     * 速度阈值
     **/
    private String speedThreshold;

    /**
     * 一级报警使能
     **/
    private Integer oneLevelAlarmEnable;

    /**
     * 二级报警使能
     **/
    private Integer twoLevelAlarmEnable;

    /**
     * 录制时间
     **/
    private Integer videoRecordingTime;

    /**
     * 拍照张数
     **/
    private Integer photographNumber;

    /**
     * 拍照间隔
     **/
    private Integer photographTime;

    /**
     * 时距阈值
     **/
    private Integer timeDistanceThreshold;

    /**
     * 时间段阈值
     **/
    private Integer timeSlotThreshold;

    /**
     * 报警分级速度阈值
     **/
    private Integer alarmLevelSpeedThreshold;

    /**
     * 次数阈值
     **/
    private Integer frequencyThreshold;

    /**
     * 触发状态0:不开启,1:定时拍照,2:定距拍照,3:插卡触发
     **/
    private Integer touchStatus;

    /**
     * 道路标识识别使能
     **/
    private Integer roadSignRecognition;

    /**
     * 主动拍照使能
     */
    private Integer initiativePictureEnable;

    /**
     * 驾驶员更换事件使能
     */
    private Integer driverChangeEnable;
    /**
     * 离线人脸对比使能
     */
    private Integer offlineFaceCompareEnable;
    /**
     * 语音播报比对结果使能
     */
    private Integer voiceBroadcastComparisonEnable;
    /**
     * DSM人脸比对成功阀值(1%)
     */
    private Integer dsmCompareSuccessPercent;
    /**
     * 手机人脸比对成功阀值(1%)
     */
    private Integer phoneCompareSuccessPercent;

    /**
     *车厢过道行人监测
     */
    private Integer pedestrianInspect;


    /**
     * 默认为 1 0:表示删除
     **/
    private Integer flag = 1;

    /**
     * 道路标识超限报警使能
     **/
    private Integer roadSignEnable;

    /**
     * 标签页
     */
    private Integer paramType;

    /*****************************胎压分割线************************/
    /**
     * 轮胎型号
     */
    private String tyreNumber;

    /**
     * 轮胎型号
     */
    private String tyreNumberName;

    /**
     * 胎压单位
     */
    private Integer unit;

    /**
     * 正常胎压值
     */
    private Integer pressure;

    /**
     * 胎压不平衡门限
     */
    private Integer pressureThreshold;

    /**
     * 慢漏气门限
     */
    private Integer slowLeakThreshold;

    /**
     * 低压阈值
     */
    private Integer lowPressure;

    /**
     * 高压阈值
     */
    private Integer highPressure;

    /**
     * 高温阈值
     */
    private Integer highTemperature;

    /**
     * 电压阈值
     */
    private Integer electricityThreshold;

    /**
     * 定时上报时间间隔
     */
    private Integer uploadTime;

    /*****************************盲区分割线************************/
    /**
     * 后侧距离阈值
     */
    private Integer rear;

    /**
     * 侧后方距离阈值
     */
    private Integer sideRear;

    /*****************************吉标分割线************************/

    /**
     * 主码流视频通道
     */
    private Integer primaryChannel;

    /**
     * 子码流视频通道
     */
    private Integer subcodeChannel;

    /**
     * 抓拍视频通道
     */

    private Integer captureChannel;

    /*****************************浙标分割线************************/
    /**
     * 日间连续驾驶时间阀值
     */
    private Integer dayTime;

    /**
     * 夜间连续驾驶时间阀值
     */
    private Integer nightTime;

    /**
     * 最小停车休息时间阀值
     */
    private Integer minStopTime;

    /**
     * 夜间定义时段
     */
    private Integer nightTimeValue;

    /**
     * 24小时累计驾驶时间阀值
     */
    private Integer oneDayDriveTime;

    /************************************沪标分割线*************************************/

    /**
     * 拍照分辨率
     */
    private String cameraResolution;

    /**************************************中位标准分割线********************************/

    /**
     * 一级语音提醒
     **/
    private Integer oneLevelVoiceReminder;

    /**
     * 二级语音提醒
     **/
    private Integer twoLevelVoiceReminder;

    /**
     * 一级辅助多媒体
     **/
    private Integer oneLevelAuxiliaryMultimedia;

    /**
     * 二级辅助多媒体
     **/
    private Integer twoLevelAuxiliaryMultimedia;

    /**
     * 辅助信息语音提示使能
     **/
    private Integer voiceReminderEnable;

    /**
     * 辅助使能
     **/
    private Integer auxiliaryEnable;

    /**
     * 补传使能
     */
    private Integer compensatingEnable;

    /**
     * 滤波系数
     */
    private Integer smoothing;

    /**
     * 自动上传时间
     */
    private Integer automaticUploadTime;

    /**
     * 修正系数K
     */
    private Integer compensationFactorK;

    /**
     * 修正系数B
     */
    private Integer compensationFactorB;

    /**
     * 左侧距离阈值
     */
    private Integer leftDistance;

    /**
     * 右侧距离阈值
     */
    private Integer rightDistance;
    /**************************************黑标新增预警时间阈值********************************/
    /**
     * 预警时间阈值
     */
    private Integer warningTimeThreshold;

}