package com.zw.adas.domain.define.setting;

import lombok.Data;

import java.io.Serializable;
import java.util.UUID;

/**
 * generated by gfw
 * Date: Tue Jun 11 09:29:49 CST 2019
 * @author gfw
 */

@Data
public class AdasCommonParamSetting implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 表id
     */
    private String id = UUID.randomUUID().toString();

    /**
     * 车辆id
     **/
    private String vehicleId;

    /**
     * 速度阈值
     **/
    private Integer speedLimit;

    /**
     * 拍照分辨率
     **/
    private String cameraResolution;

    /**
     * 视频分辨率
     **/
    private String videoResolution;

    /**
     * 提示音量
     **/
    private String alarmVolume;

    /**
     * 触发状态( 0:不开启,1:定时拍照,2:定距拍照,3:插卡触发
     **/
    private String touchStatus;

    /**
     * 拍照张数
     **/
    private Integer photographNumber;

    /**
     * 拍照间隔
     **/
    private Integer photographTime;

    /**
     * 定时拍照时间间隔
     **/
    private String timingPhotoInterval;

    /**
     * 定距拍照时间间隔
     **/
    private String distancePhotoInterval;

    /****************************中位标准新增的公告参数开始位置***************************************/
    /**
     * 灵敏度
     */
    private Integer sensitivity;

    /**
     * 前后视频录制时间
     */
    private Integer recordingTime;

    /**
     * 执行摄像头1通道号
     */
    private String channelOne;

    /**
     * 执行摄像头2通道号
     */
    private String channelTwo;

    /**
     * 执行摄像头3通道号
     */
    private String channelThree;

    /****************************中位标准新增的公告参数结束位置***************************************/

    /**
     * 默认为 1 0:表示删除
     **/
    private Integer flag = 1;

    /**
     * 协议类型
     **/
    private Integer protocolType;

    /**
     * 报警指令类型 (页签 64 65 70等)
     **/
    private Integer paramType;

    /****************************黑标新增的动态对比间隔参数开始位置***************************************/
    /**
     * 动态对比间隔
     */
    private Integer dynamicContrastInterval;
}
